#this is the main playbook
---

- name: apply common configuration to all hosts
  hosts: all
  remote_user: "{{ user }}"
  sudo: yes

  vars_prompt:
    - name: Enter your device's username
      prompt: "user"
      private: no

    - name: "rpc_username"
      prompt: Enter a username for Transmission web interface
      private: no

    - name: "rpc_password"
      prompt: Enter a password for Transmission web interface
      private: yes

  roles:
    - common
    - transmission
    - minidlna
