#this is the main playbook
---

- name: apply common configuration to all hosts
  hosts: all
  connection: local
  remote_user: pi
  sudo: yes

  vars_prompt:
    - name: "rpc_username"
      prompt: "Enter a username for Transmission admin"
      private: no

    - name: "rpc_password"
      prompt: "Enter a password for Transmission admin"
      private: yes

  roles:
    - common
    - transmission
    - minidlna
