---
- name: install minidlna
  apt: name=minidlna state=present update_cache=yes

- name: add minidlna to media group
  user: name=minidlna groups=media append=yes

- name: stop minidlna before editing settings
  service: name=minidlna state=stopped

- name: copy minidlna config into place
  template: >
            src=minidlna.conf
            dest=/etc/minidlna.conf
            mode=0644 
            group=minidlna
            owner=minidlna

- name: start minidlna back up
  service: name=minidlna state=started
